### ISSUE TITLE
Why does the output of the function 'neural_net_vessel1' go to the exponential of A?

### ISSUE THREAD

**Issue by YouqiongLiu** [PredictiveIntelligenceLab/1DBloodFlowPINNs#1]
The valuable and enlightening research. and I've got a question to consult you.
Why does the output of the function 'neural_net_vessel1' go to the exponential of A ?
As follows,
def neural_net_vessel1(self, x, t):
        Au = self.neural_net(tf.concat([x,t],1),self.weights1,self.biases1,self.layers)
        A = Au[:,0:1]
        u = Au[:,1:2]
        p = Au[:,2:3]
        return tf.exp(A), u, p

I'm looking forward to your reply soon.

**Comment by hieronimoDos** [comment]
A is the area and it should always be non-negative. For this reason, we use a trick where we consider that the neural net prediction as the logarithm of the area and compute its exponential. So, this exponential you see here is used to cancel the logarithm. This trick, meaning tf.exp(A) where A is tf.log(A), always provides non-negative predictions.

**Comment by YouqiongLiu** [comment]
> A is the area and it should always be non-negative. For this reason, we use a trick where we consider that the neural net prediction as the logarithm of the area and compute its exponential. So, this exponential you see here is used to cancel the logarithm. This trick, meaning tf.exp(A) where A is tf.log(A), always provides non-negative predictions.

What a good idea! Thanks.
For the prototype Y-shaped bifurcation, I cannot run the program 'Y_shaped.py' to reproduce the result as shown in Figure 6 in paper.
Is there any skill in here?

**Comment by hieronimoDos** [comment]
You need to run the code for a larger number of iterations. You need to change lines 103 and 104 in 'Y_shaped.py' 

    model.train(1,1e-3)
    model.train(2,1e-4)

to 

    model.train(90000,1e-3)
    model.train(40000,1e-4)

You can also check the paper to see the training details. I will correct the code to resolve any confusion.

**Comment by YouqiongLiu** [comment]
> You need to run the code for a larger number of iterations. You need to change lines 103 and 104 in 'Y_shaped.py'
> 
> ```
> model.train(1,1e-3)
> model.train(2,1e-4)
> ```
> 
> to
> 
> ```
> model.train(90000,1e-3)
> model.train(40000,1e-4)
> ```
> 
> You can also check the paper to see the training details. I will correct the code to resolve any confusion.

Thanks. I've only trained 40,000 times before.

**Comment by hieronimoDos** [comment]
I will close this for now and if you need more help send me an email.
